#include "editor/EditorHudNodeInspector.h"

#include "editor/EditorPanelStyle.h"
#include "editor/EditorWorkspace.h"

#include <imgui.h>

#include <algorithm>
#include <cstring>

namespace demi::editor {
namespace {

void setVec2(EditorWorkspace &workspace, const runtime::ui::UiNode &node,
             const char *field, const float values[2], std::string message,
             std::string &notice) {
  std::string error;
  notice =
      workspace.setHudNodeField(
          node.id, field, nlohmann::json::array({values[0], values[1]}), error)
          ? std::move(message)
          : error;
}

} // namespace

void drawEditorHudNodeInspector(EditorWorkspace &workspace,
                                const ImVec2 position, const ImVec2 size,
                                EditorHudInspectorState &state,
                                std::string &notice) {
  beginEditorPanel("HudNodeInspector", position, size);
  if (ImGui::BeginTabBar("hud-inspector-tabs")) {
    if (ImGui::BeginTabItem("Inspector"))
      ImGui::EndTabItem();
    ImGui::EndTabBar();
  }

  const runtime::ui::UiNode *selectedNode = workspace.selectedHudNode();
  if (selectedNode == nullptr) {
    ImGui::TextDisabled("The selected HUD element no longer exists.");
    ImGui::End();
    return;
  }
  const runtime::ui::UiNode node = *selectedNode;
  const EditorHudDocument *document = workspace.hudDocument();
  const bool authored =
      document != nullptr && document->authoredNode(node.id) != nullptr;
  if (state.nodeId != node.id) {
    state = {};
    state.nodeId = node.id;
    std::strncpy(state.text.data(), node.text.c_str(), state.text.size() - 1);
    std::strncpy(state.texture.data(), node.texture.c_str(),
                 state.texture.size() - 1);
  }

  ImGui::TextUnformatted(node.id.c_str());
  ImGui::TextDisabled("HUD element · %s", node.type.c_str());
  if (!authored)
    ImGui::TextColored({0.91F, 0.68F, 0.30F, 1.0F}, "Generated by a UI prefab");
  ImGui::Separator();

  ImGui::CollapsingHeader("UI Element", ImGuiTreeNodeFlags_DefaultOpen);
  ImGui::TextDisabled("Parent");
  ImGui::SameLine(105.0F);
  ImGui::TextUnformatted(node.parent.empty() ? "HUD root"
                                             : node.parent.c_str());
  ImGui::BeginDisabled(!authored);
  bool visible = node.visible;
  if (ImGui::Checkbox("Visible", &visible)) {
    std::string error;
    notice = workspace.setHudNodeField(node.id, "visible", visible, error)
                 ? "HUD visibility modified"
                 : error;
  }
  bool respectsSafeArea = node.respectsSafeArea;
  if (ImGui::Checkbox("Respect Safe Area", &respectsSafeArea)) {
    std::string error;
    notice = workspace.setHudNodeField(node.id, "respect_safe_area",
                                       respectsSafeArea, error)
                 ? "HUD safe-area behavior modified"
                 : error;
  }
  if (!respectsSafeArea)
    ImGui::TextDisabled("Layout uses the full screen behind cutouts.");
  ImGui::EndDisabled();
  ImGui::BeginDisabled(!authored);
  if (node.type == "label" || node.type == "button" ||
      node.type == "text_input") {
    if (ImGui::InputText("Text", state.text.data(), state.text.size(),
                         ImGuiInputTextFlags_EnterReturnsTrue)) {
      std::string error;
      notice =
          workspace.setHudNodeField(node.id, "text", state.text.data(), error)
              ? "HUD text modified"
              : error;
    }
    float fontSize = node.fontSize;
    if (ImGui::InputFloat("Font Size", &fontSize, 1.0F, 4.0F, "%.1f")) {
      std::string error;
      notice = workspace.setHudNodeField(node.id, "font_size",
                                         std::max(fontSize, 1.0F), error)
                   ? "HUD font size modified"
                   : error;
    }
  }
  if (node.type == "image" &&
      ImGui::InputText("Texture", state.texture.data(), state.texture.size(),
                       ImGuiInputTextFlags_EnterReturnsTrue)) {
    std::string error;
    notice = workspace.setHudNodeField(node.id, "texture", state.texture.data(),
                                       error)
                 ? "HUD texture modified"
                 : error;
  }
  float background[4]{node.backgroundColor.r, node.backgroundColor.g,
                      node.backgroundColor.b, node.backgroundColor.a};
  if (ImGui::ColorEdit4("Background", background)) {
    std::string error;
    notice = workspace.setHudNodeField(
                 node.id, "background_color",
                 nlohmann::json::array({background[0], background[1],
                                        background[2], background[3]}),
                 error)
                 ? "HUD background modified"
                 : error;
  }
  ImGui::EndDisabled();

  ImGui::CollapsingHeader("Rect Transform", ImGuiTreeNodeFlags_DefaultOpen);
  ImGui::BeginDisabled(!authored);
  float nodePosition[2]{node.layout.position.x, node.layout.position.y};
  if (ImGui::InputFloat2("Position", nodePosition, "%.1f"))
    setVec2(workspace, node, "position", nodePosition, "HUD position modified",
            notice);
  float nodeSize[2]{node.layout.size.x, node.layout.size.y};
  if (ImGui::InputFloat2("Size", nodeSize, "%.1f")) {
    nodeSize[0] = std::max(nodeSize[0], 0.0F);
    nodeSize[1] = std::max(nodeSize[1], 0.0F);
    setVec2(workspace, node, "size", nodeSize, "HUD size modified", notice);
  }
  float anchorMin[2]{node.layout.anchorMin.x, node.layout.anchorMin.y};
  if (ImGui::InputFloat2("Anchor Min", anchorMin, "%.2f")) {
    anchorMin[0] = std::clamp(anchorMin[0], 0.0F, 1.0F);
    anchorMin[1] = std::clamp(anchorMin[1], 0.0F, 1.0F);
    setVec2(workspace, node, "anchor_min", anchorMin, "HUD anchors modified",
            notice);
  }
  float anchorMax[2]{node.layout.anchorMax.x, node.layout.anchorMax.y};
  if (ImGui::InputFloat2("Anchor Max", anchorMax, "%.2f")) {
    anchorMax[0] = std::clamp(anchorMax[0], 0.0F, 1.0F);
    anchorMax[1] = std::clamp(anchorMax[1], 0.0F, 1.0F);
    setVec2(workspace, node, "anchor_max", anchorMax, "HUD anchors modified",
            notice);
  }
  ImGui::EndDisabled();
  ImGui::TextDisabled("Resolved: %.1f, %.1f  %.1f x %.1f", node.resolved.x,
                      node.resolved.y, node.resolved.width,
                      node.resolved.height);

  ImGui::SetCursorPosY(std::max(ImGui::GetCursorPosY(), size.y - 78.0F));
  ImGui::BeginDisabled(!authored);
  if (ImGui::Button("Delete UI Element", {-1.0F, 28.0F})) {
    std::string error;
    notice =
        workspace.deleteSelectedHudNode(error) ? "HUD element deleted" : error;
  }
  ImGui::EndDisabled();
  ImGui::BeginDisabled(document == nullptr || !document->isDirty());
  if (ImGui::Button("Save HUD", {-1.0F, 28.0F})) {
    std::string error;
    notice = workspace.saveHud(error) ? "HUD saved" : error;
  }
  ImGui::EndDisabled();
  ImGui::End();
}

} // namespace demi::editor
