local Test = require("demi.test")

local Events = require("demi.gameplay.events")
local Inventory = require("demi.gameplay.inventory")

Test.case("capacity and stacks clamp", function()
  local inventory = Inventory.new(Events.new(), 1)
  Test.equal(inventory:add("coin", 8, 5), 5); Test.equal(inventory:add("key", 1), 0)
  Test.equal(inventory:remove("coin", 99), 5); Test.equal(inventory.stacks.coin, nil)
end)

Test.case("save load keeps equipment", function()
  local first = Inventory.new(Events.new()); first:add("sword"); first:equip("hand", "sword")
  local second = Inventory.new(Events.new()); Test.equal(second:load(first:save()), true)
  Test.equal(second.equipment.hand, "sword")
end)

Test.case("queries and transfers conserve accepted quantities", function()
  local events=Events.new()
  local depot,cargo=Inventory.new(events),Inventory.new(events,1)
  depot:add("metal",24)
  Test.equal(depot:transfer_to(cargo,"metal",6,4),4)
  Test.equal(depot:count("metal"),20);Test.equal(cargo:count("metal"),4)
  depot:add("meal",2)
  Test.equal(depot:transfer_to(cargo,"meal",1),0)
  Test.equal(depot:count("meal"),2)
  Test.equal(cargo:transfer_to(depot,"metal",99),4)
  Test.equal(depot:count("metal"),24);Test.equal(cargo:count("metal"),0)
  Test.equal(depot:transfer_to(depot,"metal",2),0)
end)
Test.case("bad counts and lower caps cannot create negative transfers", function()
  local events=Events.new();local source,target=Inventory.new(events),Inventory.new(events)
  source:add("metal",5);target:add("metal",4)
  Test.equal(source:transfer_to(target,"metal",3,2),0)
  Test.equal(source:count("metal"),5);Test.equal(target:count("metal"),4)
  Test.equal(source:add("metal",0/0),0)
  Test.equal(source:remove("metal",math.huge),0)
  Test.equal(source:transfer_to(target,"metal",-1),0)
end)
