local Test = require("demi.test")
local Hud = require("demi.hud")
local Entity = require("demi.entity")
local Transform3D = require("demi.transform3d")
local Camera = require("demi.camera3d")
local Physics = require("demi.physics.query3d")
local Input = require("demi.input")

local function read_amount(id)
  local text = Hud.get_text(id) or ""
  local amount = tonumber(text:match("[%+%-]?%d+"))
  Test.expect(amount ~= nil, "Resource HUD contains a number: " .. id)
  return amount
end

local function tap_world(x, z)
  local ground = Physics.raycast(x,500,z,0,-1,0,1000)
  Test.expect(ground ~= nil, "World target has a surface")
  local w,h = Input.viewport_size()
  local screen = Camera.world_to_screen("camera",x,ground.point[2],z,w,h)
  Test.expect(screen ~= nil, "World target projects into camera depth")
  local cw,ch = Hud.canvas_size()
  Test.expect(screen[2]/h < 0.72 and screen[2]/h > 0.12, "Test site overlaps HUD: " .. x .. "," .. z .. " y=" .. screen[2]/h)
  Test.tap(screen[1]/w*cw,screen[2]/h*ch)
  Test.wait(0.3)
end

return { tests = {
  {
    name = "colony_life_support_and_construction",
    func = function()
      Test.expect_scene("scene://colony")
      Test.wait(0.3)
      Test.expect(Test.node_center("label") ~= nil, "Power readout exists")
      Test.expect(read_amount("label") == 4, "Default colony has 4 kW surplus")
      local water = read_amount("label_copy")
      local oxygen = read_amount("label_copy_copy")
      local x, y, z = Transform3D.get_position("camera")
      Test.wait(2)
      local later_water = read_amount("label_copy")
      local later_oxygen = read_amount("label_copy_copy")
      Test.expect(later_water > water and later_water <= 100, "Water production reaches HUD")
      Test.expect(later_oxygen > oxygen and later_oxygen <= 100, "Powered oxygen production reaches HUD")
      local nx, ny, nz = Transform3D.get_position("camera")
      Test.expect(nx == x and ny == y and nz == z, "Camera stays still without input")

      local config = Entity.get_config("ent_new", "LuaScript", "properties")
      Test.expect(Entity.exists(config.solar_array), "Solar reference survives prefab conversion")
      Test.expect(Entity.exists(config.water_extractor), "Water extractor reference resolves")
      Test.expect(Entity.set_enabled(config.solar_array, false), "Disable solar array")
      Test.wait(0.3)
      Test.expect(read_amount("label") == -8, "Disabled solar array removes supply")
      local stopped_water = read_amount("label_copy")
      local stopped_oxygen = read_amount("label_copy_copy")
      Test.wait(2)
      Test.expect(read_amount("label_copy") == stopped_water, "No water production or oxygen-generator consumption without power")
      Test.expect(read_amount("label_copy_copy") < stopped_oxygen, "Oxygen falls without power")

      Test.expect(Entity.set_enabled(config.solar_array, true), "Restore solar array")
      Test.expect(Entity.set_enabled(config.water_extractor, false), "Disable extractor")
      Test.wait(0.3)
      local stored_water = read_amount("label_copy")
      Test.wait(2)
      Test.expect(read_amount("label") == 4, "Power recovers independently of extraction")
      Test.expect(read_amount("label_copy") < stored_water, "Oxygen production consumes stored water while extraction is disabled")
      Test.expect(Entity.set_enabled(config.water_extractor, true), "Restore extractor")
      local before_recovery = read_amount("label_copy")
      Test.wait(2)
      Test.expect(read_amount("label_copy") > before_recovery, "Water production recovers")

      Test.touch("build_solar")
      Test.wait(0.2)
      Test.expect(read_amount("metal")==24, "Selecting a plan spends no metal")
      tap_world(82.822,77.408)
      Test.expect(not Entity.exists("built_1/base"), "Occupied habitat site is rejected")
      Test.expect(read_amount("metal")==24, "Rejected placement is free")
      Test.touch("build_cancel")
      Test.wait(0.2)
      tap_world(88,88)
      Test.expect(not Entity.exists("built_1/base"), "Cancel prevents world placement")
      Test.touch("build_solar")
      Test.wait(0.2)
      tap_world(88,88)
      Test.expect(Entity.exists("built_1/base"), "Solar prefab constructed: " .. (Hud.get_text("construction.status") or ""))
      Test.expect(read_amount("metal")==18, "Solar cost charged exactly once")
      Test.expect(read_amount("label")==16, "New array adds 12 kW to life support")
      Test.touch("build_water")
      Test.wait(0.2)
      tap_world(80,90)
      Test.expect(Entity.exists("built_2/base"), "Extractor prefab constructed: " .. (Hud.get_text("construction.status") or ""))
      Test.expect(read_amount("metal")==10, "Extractor cost charged exactly once")
      Test.expect(read_amount("label")==14, "New extractor consumes 2 kW")
      Test.expect(Entity.set_enabled("built_1/base",false), "Disable constructed solar root")
      Test.wait(0.3)
      Test.expect(read_amount("label")==2, "Disabled constructed solar stops producing")
      Test.expect(Entity.set_enabled("built_1/base",true), "Restore constructed array")
      Test.touch("build_solar")
      Test.wait(0.2)
      tap_world(72,72)
      Test.expect(Entity.exists("built_3/base") and read_amount("metal")==4, "Second solar uses remaining affordable metal")
      Test.touch("build_water")
      Test.wait(0.2)
      tap_world(70,88)
      Test.expect(not Entity.exists("built_4/base") and read_amount("metal")==4, "Unaffordable construction neither spawns nor spends")
      Test.expect((Hud.get_text("construction.status") or ""):find("Not enough metal",1,true), "Insufficient material feedback reaches the HUD")
      Test.touch("build_cancel")
    end,
  },
} }
