local Test = require("demi.test")
local Hud = require("demi.hud")
local Entity = require("demi.entity")
local Transform3D = require("demi.transform3d")
local Camera = require("demi.camera3d")
local Physics = require("demi.physics.query3d")
local Input = require("demi.input")

local function read_amount(id)
  local text = Hud.get_text(id) or ""
  local amount = tonumber(text:match("[%+%-]?%d+"))
  Test.expect(amount ~= nil, "Resource HUD contains a number: " .. id)
  return amount
end

local function tap_world(x, z)
  local ground = Physics.raycast(x,500,z,0,-1,0,1000)
  Test.expect(ground ~= nil, "World target has a surface")
  local w,h = Input.viewport_size()
  local screen = Camera.world_to_screen("camera",x,ground.point[2],z,w,h)
  Test.expect(screen ~= nil, "World target projects into camera depth")
  local cw,ch = Hud.canvas_size()
  Test.expect(screen[2]/h < 0.72 and screen[2]/h > 0.12, "Test site overlaps HUD: " .. x .. "," .. z .. " y=" .. screen[2]/h)
  Test.tap(screen[1]/w*cw,screen[2]/h*ch)
  Test.wait(0.3)
end

local function wait_for(predicate,message,seconds)
  for _=1,(seconds or 35)*4 do
    if predicate() then return end
    Test.wait(0.25)
  end
  Test.expect(false,message .. " / " .. (Hud.get_text("job_status") or ""))
end
local function link(action,ax,az,bx,bz)
  Test.touch(action);Test.wait(0.2)
  tap_world(ax,az);tap_world(bx,bz)
end

return { tests = {
  {
    name = "colony_connections_and_engineer_jobs",
    func = function()
      Test.expect_scene("scene://colony")
      Test.wait(0.3)
      Test.expect(Test.node_center("label") ~= nil, "Power readout exists")
      Test.expect(read_amount("label") == 4, "Default colony has 4 kW surplus")
      local water = read_amount("label_copy")
      local oxygen = read_amount("label_copy_copy")
      local x, y, z = Transform3D.get_position("camera")
      Test.wait(2)
      local later_water = read_amount("label_copy")
      local later_oxygen = read_amount("label_copy_copy")
      Test.expect(later_water > water and later_water <= 100, "Water production reaches HUD")
      Test.expect(later_oxygen > oxygen and later_oxygen <= 100, "Powered oxygen production reaches HUD")
      local nx, ny, nz = Transform3D.get_position("camera")
      Test.expect(nx == x and ny == y and nz == z, "Camera stays still without input")

      local config = Entity.get_config("ent_new", "LuaScript", "properties")
      Test.expect(Entity.exists(config.solar_array), "Solar reference survives prefab conversion")
      Test.expect(Entity.exists(config.water_extractor), "Water extractor reference resolves")
      Test.expect(Entity.set_enabled(config.solar_array, false), "Disable solar array")
      Test.wait(0.3)
      Test.expect(read_amount("label") == -8, "Disabled solar array removes supply")
      local stopped_water = read_amount("label_copy")
      local stopped_oxygen = read_amount("label_copy_copy")
      Test.wait(2)
      Test.expect(read_amount("label_copy") == stopped_water, "No water production or oxygen-generator consumption without power")
      Test.expect(read_amount("label_copy_copy") < stopped_oxygen, "Oxygen falls without power")

      Test.expect(Entity.set_enabled(config.solar_array, true), "Restore solar array")
      Test.expect(Entity.set_enabled(config.water_extractor, false), "Disable extractor")
      Test.wait(0.3)
      local stored_water = read_amount("label_copy")
      Test.wait(2)
      Test.expect(read_amount("label") == 6, "Disabled extractor stops its power draw")
      Test.expect(read_amount("label_copy") < stored_water, "Oxygen production consumes stored water while extraction is disabled")
      Test.expect(Entity.set_enabled(config.water_extractor, true), "Restore extractor")
      local before_recovery = read_amount("label_copy")
      Test.wait(2)
      Test.expect(read_amount("label_copy") > before_recovery, "Water production recovers")

      Test.expect(Entity.exists("engineer"), "Authored engineer exists")
      Test.expect(Entity.set_enabled("engineer",false), "Pause engineer")
      local worker=Entity.world_position("engineer")
      Test.touch("build_solar");Test.wait(0.2)
      tap_world(82.822,77.408)
      Test.expect(not Entity.exists("site_1/base") and read_amount("metal")==24, "Occupied sites do not reserve resources")
      Test.touch("build_cancel");tap_world(88,88)
      Test.expect(not Entity.exists("site_1/base"), "Leaving placement mode creates no site")
      Test.touch("build_solar");tap_world(88,88)
      Test.expect(Entity.exists("site_1/base") and not Entity.exists("built_1/base"), "Plan creates a work site, not a finished building")
      Test.expect(read_amount("metal")==18 and read_amount("label")==4, "Reserve cost without premature power")
      Test.wait(1)
      local paused=Entity.world_position("engineer")
      Test.expect(paused[1]==worker[1] and paused[3]==worker[3] and not Entity.exists("built_1/base"), "Disabled engineer does not move or finish jobs")
      Test.expect(Entity.set_enabled("engineer",true), "Resume engineer")
      Test.wait(1)
      local moving=Entity.world_position("engineer")
      local travelled=math.sqrt((moving[1]-worker[1])^2+(moving[3]-worker[3])^2)
      Test.expect(travelled>0.1 and travelled<4, "Engineer walks at bounded speed instead of teleporting")
      wait_for(function() return Entity.exists("built_1/base") end,"Solar construction completes")
      Test.expect(not Entity.exists("site_1/base"), "Finished job removes its scaffold")
      Test.expect(read_amount("label")==4, "Disconnected solar produces no colony power")
      link("build_connect",82.822,77.408,88,88)
      Test.expect(read_amount("metal")==17, "Connection reserves one metal")
      Test.expect(read_amount("label")==4, "Pending cable does not connect utilities")
      wait_for(function() return read_amount("label")==16 end,"Finished connection activates solar")
      link("build_disconnect",82.822,77.408,88,88)
      Test.expect(read_amount("label")==4 and not Entity.exists("connection_1"), "Disconnect removes link and its power")
      link("build_connect",82.822,77.408,88,88)
      wait_for(function() return read_amount("label")==16 end,"Reconnect restores power")
      link("build_connect",82.822,77.408,88,88)
      Test.expect(read_amount("metal")==16, "Duplicate connections cost nothing")
      Test.touch("build_water");tap_world(80,90)
      Test.expect(Entity.exists("site_2/base") and read_amount("metal")==8,"Extractor plan reserves metal")
      Test.touch("build_cancel");Test.wait(0.3)
      Test.expect(not Entity.exists("site_2/base") and read_amount("metal")==16,"Cancelling a queued or active job refunds reserved metal")
      Test.touch("build_water");tap_world(80,90)
      wait_for(function() return Entity.exists("built_3/base") end,"Extractor construction completes")
      Test.expect(read_amount("label")==16,"Disconnected extractor draws no colony power")
      link("build_connect",88,88,80,90)
      wait_for(function() return read_amount("label")==14 end,"Transitive connection brings extractor online")
      Test.expect(Entity.set_enabled("built_1/base",false),"Disable bridge utility")
      Test.wait(0.4)
      Test.expect(read_amount("label")==4,"Offline bridge disconnects downstream extractor")
      Test.expect(Entity.set_enabled("built_1/base",true),"Restore bridge utility")
      Test.wait(0.4)
      Test.expect(read_amount("label")==14,"Bridge recovery restores downstream service")
      Test.touch("build_water");tap_world(70,88)
      Test.expect(not Entity.exists("site_4/base") and read_amount("metal")==7,"Insufficient metal creates no site")
      Test.touch("build_cancel")
    end,
  },
} }
