# Program handles are reused. Bindings absent from the replacement shaders must
# not retain descriptor information from the previous program. Applies to the
# shared Vulkan backend on every platform, not a vendor-specific workaround.
if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()
set(target_file "${SOURCE_DIR}/bgfx/src/renderer_vk.cpp")
file(READ "${target_file}" source)
set(original "\t\tfor (uint8_t stage = 0; stage < BX_COUNTOF(m_bindInfo); ++stage)\n\t\t{\n\t\t\tconst ShaderVK* shader = NULL;")
set(replacement "\t\tfor (uint8_t stage = 0; stage < BX_COUNTOF(m_bindInfo); ++stage)\n\t\t{\n\t\t\t// Demi reset reused Vulkan program bindings.\n\t\t\tm_bindInfo[stage].uniformHandle  = BGFX_INVALID_HANDLE;\n\t\t\tm_bindInfo[stage].type           = BindType::Count;\n\t\t\tm_bindInfo[stage].binding        = 0;\n\t\t\tm_bindInfo[stage].samplerBinding = 0;\n\t\t\tm_bindInfo[stage].index          = UINT32_MAX;\n\t\t\tconst ShaderVK* shader = NULL;")
string(FIND "${source}" "${replacement}" patched)
if(NOT patched EQUAL -1)
  string(FIND "${source}" "${original}" unpatched)
  if(NOT unpatched EQUAL -1)
    message(FATAL_ERROR "Mixed patched/unpatched Vulkan program binding loops")
  endif()
  return()
endif()
string(FIND "${source}" "${original}" found)
if(found EQUAL -1)
  message(FATAL_ERROR "Pinned bgfx Vulkan program binding loop changed; review the binding reset patch")
endif()
string(REPLACE "${original}" "" without_match "${source}")
string(LENGTH "${source}" source_length)
string(LENGTH "${without_match}" remaining_length)
string(LENGTH "${original}" match_length)
math(EXPR matched_length "${source_length} - ${remaining_length}")
if(NOT matched_length EQUAL match_length)
  message(FATAL_ERROR "Expected one pinned Vulkan program binding loop")
endif()
string(REPLACE "${original}" "${replacement}" source "${source}")
file(WRITE "${target_file}" "${source}")
