# Instrument the pinned backend without hand-editing a fetched checkout.
if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()
set(target_file "${SOURCE_DIR}/bgfx/src/renderer_vk.cpp")
file(READ "${target_file}" source)
if(NOT source MATCHES "Demi uniform-flush timing")
  set(original "\tvoid ChunkedScratchBufferVK::flushChunk(ChunkVK& _chunk, uint32_t _size)\n\t{")
  string(FIND "${source}" "${original}" location)
  if(location EQUAL -1)
    message(FATAL_ERROR "Pinned bgfx uniform-flush anchor not found")
  endif()
  string(REPLACE "${original}" "${original}\n\t\t// Demi uniform-flush timing\n\t\tBGFX_PROFILER_SCOPE(\"vkUniformFlush\", kColorResource);" source "${source}")
  file(WRITE "${target_file}" "${source}")
endif()
file(READ "${target_file}" source)
if(NOT source MATCHES "Demi memory-budget timing")
  set(original "\t\t\tvkGetPhysicalDeviceMemoryProperties2KHR(m_physicalDevice, &pdmp2);")
  string(FIND "${source}" "${original}" location)
  if(location EQUAL -1)
    message(FATAL_ERROR "Pinned bgfx memory-budget query anchor not found")
  endif()
  set(replacement "\t\t\t{ // Demi memory-budget timing\n\t\t\t\tBGFX_PROFILER_SCOPE(\"vkMemoryBudget\", kColorResource);\n\t\t\t\tvkGetPhysicalDeviceMemoryProperties2KHR(m_physicalDevice, &pdmp2);\n\t\t\t}")
  string(REPLACE "${original}" "${replacement}" source "${source}")
  file(WRITE "${target_file}" "${source}")
endif()
