local Character = require("demi.gameplay.third_person")
local Orbit = require("demi.gameplay.orbit_camera")
local Melee = require("demi.gameplay.melee")

Test.case("damage is active-only and a dodged swing cannot re-hit", function()
  local attack = Melee.new({windup=0.5,active=0.2,recovery=1,reach=3,damage=20})
  Test.equal(attack:start(),true)
  Test.equal(attack:hit("player",1,1,false),0)
  attack:update(0.5)
  Test.equal(attack:hit("player",1,-1,false),0)
  Test.equal(attack:hit("player",1,1,true),0)
  Test.equal(attack:hit("player",1,1,false),0)
  Test.equal(attack:hit("second",1,1,false),20)
  Test.equal(attack:hit("second",1,1,false),0)
  attack:update(0.21)
  Test.equal(attack:hit("third",1,1,false),0)
  Test.equal(attack:start(),false)
  attack:update(1)
  Test.equal(attack:start(),true)
end)

Test.case("roll protects startup, expires, costs stamina and locks direction", function()
  local c = Character.new()
  c:update({x=1,roll=true},0,-1,0.01,false)
  Test.equal(c:invulnerable(),true)
  Test.equal(c.stamina,75)
  c:update({x=-1},1,0,0.1,false)
  Test.equal(c.vx,7)
  Test.equal(c.vz,0)
  c:update({},0,-1,0.3,false)
  Test.equal(c:invulnerable(),false)
  c:update({},0,-1,0.3,false)
  Test.equal(c.roll_left,0)
end)

Test.case("camera basis normalizes diagonals and respects nearby obstruction", function()
  local c = Character.new()
  c:update({x=1,y=1},0,-1,0.01,false)
  Test.near(math.sqrt(c.vx*c.vx+c.vz*c.vz),4)
  local orbit = Orbit.new({clearance=0.08})
  local eye,focus = orbit:position({x=0,y=1,z=0},function() return 0.1 end)
  local x,y,z = eye.x-focus.x,eye.y-focus.y,eye.z-focus.z
  Test.near(math.sqrt(x*x+y*y+z*z),0.02)
  local before = orbit.yaw
  orbit:look(100,0,{x=0,z=0})
  Test.equal(orbit.yaw < before,true)
end)
