local pack_loaded, pack = pcall(require, "generated.pack_import")
if not pack_loaded then
  pack = {
    texture = "",
    atlas_columns = 14,
    blocks = {
      [1] = { top = 0, side = 1, bottom = 2 },
      [2] = { top = 2, side = 2, bottom = 2 },
      [3] = { top = 3, side = 3, bottom = 3 },
      [4] = { top = 5, side = 4, bottom = 5 },
      [5] = { top = 6, side = 6, bottom = 6 },
      [6] = { top = 7, side = 7, bottom = 7 },
      [7] = { top = 8, side = 8, bottom = 8 },
      [8] = { top = 9, side = 9, bottom = 9 },
      [9] = { top = 10, side = 10, bottom = 10 },
      [10] = { top = 11, side = 11, bottom = 11 },
      [11] = { top = 12, side = 12, bottom = 12 },
      [12] = { top = 13, side = 13, bottom = 13 },
    },
  }
end

return {
  pack = pack,
  chunk_size = 32,
  section_height = 32,
  load_radius = 6,
  unload_radius = 7,
  vertical_load_radius = 3,
  vertical_unload_radius = 4,
  camera_id = "ent_camera",
  selection_id = "ent_block_selection",
  benchmark_enabled = os.getenv("DEMI_VOXEL_BENCH") == "1",
  benchmark_step = 1.0,
  chunk_load_budget = tonumber(os.getenv("DEMI_VOXEL_CHUNK_LOADS_PER_FRAME") or "") or 1,
  chunk_unload_budget = tonumber(os.getenv("DEMI_VOXEL_CHUNK_UNLOADS_PER_FRAME") or "") or 16,
  section_rebuild_budget = tonumber(os.getenv("DEMI_VOXEL_SECTION_REBUILDS_PER_FRAME") or "") or 1,
  chunk_process_budget_ms = tonumber(os.getenv("DEMI_VOXEL_CHUNK_PROCESS_BUDGET_MS") or "") or 6.0,
  interaction_range = 8.0,
  ray_step = 0.12,
  blocks = {
    [1] = { name = "Grass", drop = 1 },
    [2] = { name = "Dirt", drop = 2 },
    [3] = { name = "Stone", drop = 3 },
    [4] = { name = "Log", drop = 4 },
    [5] = { name = "Leaves", drop = 5 },
    [6] = { name = "Sand", drop = 6 },
    [7] = { name = "Dark Leaves", drop = 7 },
    [8] = { name = "Orange Leaves", drop = 8 },
    [9] = { name = "Grass Tuft", drop = 0, render = "cross" },
    [10] = { name = "Dandelion", drop = 0, render = "cross" },
    [11] = { name = "Daisy", drop = 0, render = "cross" },
    [12] = { name = "Blue Orchid", drop = 0, render = "cross" },
  },
  hotbar = {
    slots = { 1, 2, 3, 4, 5, 6, 7, 8, 9 },
    start_x = 300.0,
    y = 474.0,
    slot_size = 56.0,
    gap = 4.0,
  },
  performance = {
    sample_frames = 600,
    update_interval = 0.25,
  },
  terrain = {
    seed = 4242,
    landform_seed = 4242,
    landform_frequency = 0.0065,
    base_height = 63,
    flat_threshold = 0.45,
    mountain_threshold = 0.76,
    flat_amplitude = 2,
    hill_amplitude = 9,
    rolling_frequency = 0.015,
    mountain_seed = 7331,
    mountain_amplitude = 44,
    mountain_roughness_amplitude = 12,
    mountain_roughness_frequency = 0.027,
    mountain_base_lift = 8,
    rock_slope = 3,
    fill_depth = 5,
    cap_block = 1,
    fill_block = 2,
    base_block = 3,
  },
  biomes = {
    seed = 9301,
    frequency = 0.006,
    desert_threshold = 0.85,
    plains = {
      id = "plains",
      cap_block = 1,
      fill_block = 2,
      base_block = 3,
      trees = true,
    },
    desert = {
      id = "desert",
      cap_block = 6,
      fill_block = 6,
      base_block = 3,
      trees = false,
    },
  },
  trees = {
    enabled = true,
    seed = 811,
    cell_size = 13,
    chance = 0.34,
    min_height = 55,
    log_block = 4,
    variants = {
      {
        id = "dark_spruce",
        leaves_block = 7,
        trunk_height = 7,
        canopy_radius = 3,
        canopy_height = 6,
      },
      {
        id = "orange_spruce",
        leaves_block = 8,
        trunk_height = 6,
        canopy_radius = 3,
        canopy_height = 5,
      },
    },
  },
  decorations = {
    enabled = true,
    seed = 1907,
    grass_chance = 0.14,
    flower_chance = 0.035,
    grass_block = 9,
    flower_blocks = { 10, 11, 12 },
  },
}
