local Test = require("demi.test")
local Orbit = require("demi.ui.orbit")
Test.case("palette copies and explicit overrides stay independent", function()
  local first = Orbit.palette("glacier", {accent="#ABCDEF"})
  local second = Orbit.palette("glacier")
  Test.equal(first.accent, "#ABCDEF")
  Test.equal(second.accent, "#7DCBFF")
  Test.equal(pcall(function() Orbit.palette("missing") end), false)
  Test.equal(pcall(function() Orbit.palette("ember", {typo="#FFFFFF"}) end), false)
end)
Test.case("runtime buttons preserve caller identity and state", function()
  local options={disabled=true, size={180,44}, palette=Orbit.palette("glacier")}
  local button=Orbit.button("continue", "Continue", options)
  Test.equal(button.id, "continue"); Test.equal(button.prefab, "ui-prefab://orbit/button-primary")
  Test.equal(button.arguments.disabled, true); Test.equal(button.arguments.accent, "#7DCBFF")
  button.arguments.size[1]=500; Test.equal(options.size[1],180)
end)
Test.case("source definitions retain typed arguments for the shared loader", function()
  local node=Orbit.node("settings", "prefs", {volume=0.25})
  Test.equal(node.id,"prefs")
  Test.equal(node.prefab,"ui-prefab://orbit/settings")
  Test.equal(node.arguments.volume,0.25)
  Test.equal(pcall(function() Orbit.node("slider","s",{unknown=1}) end),false)
end)
Test.case("icons use stable assets and accessible button labels", function()
  local icon = Orbit.icon("status", "energy", {tint="#FFB66B", size={32,32}})
  Test.equal(icon.arguments.texture, "asset://orbit/icons/energy")
  Test.equal(icon.arguments.size[1], 32)
  local button = Orbit.icon_button("settings", "settings", "Open settings")
  Test.equal(button.arguments.label, "Open settings")
  Test.equal(button.prefab, "ui-prefab://orbit/icon-button")
  Test.equal(pcall(function() Orbit.icon_asset("unknown") end), false)
end)
